<ul class="nav nav-list aside">
	<li class="nav-header"><?= _t('sub.menu.subscription_management') ?></li>

	<li class="item<?= Base_Request::controllerName() === 'subscription' && Base_Request::actionName() !== 'bookmarklet' ? ' active' : '' ?>">
		<a href="<?= _url('subscription', 'index') ?>"><?= _t('sub.menu.subscription_management') ?></a>
	</li>

	<li class="item<?= Base_Request::controllerName() === 'importExport' ? ' active' : '' ?>">
		<a href="<?= _url('importExport', 'index') ?>"><?= _t('sub.menu.import_export') ?></a>
	</li>

	<li class="item<?= Base_Request::controllerName() === 'subscription' && Base_Request::actionName() === 'bookmarklet' ? ' active' : '' ?>">
		<a href="<?= _url('subscription', 'bookmarklet') ?>"><?= _t('sub.menu.subscription_tools') ?></a>
	</li>
</ul>
