<ul class="nav nav-list aside">
	<li class="nav-header"><?= _t('admin.stats') ?></li>
	<li class="item<?= Base_Request::actionName() == 'index' ? ' active' : '' ?>">
		<a href="<?= _url('stats', 'index') ?>"><?= _t('admin.stats.menu.main') ?></a>
	</li>
	<li class="item<?= Base_Request::actionName() == 'idle' ? ' active' : '' ?>">
		<a href="<?= _url('stats', 'idle') ?>"><?= _t('admin.stats.menu.idle') ?></a>
	</li>
	<li class="item<?= Base_Request::actionName() == 'repartition' ? ' active' : '' ?>">
		<a href="<?= _url('stats', 'repartition') ?>"><?= _t('admin.stats.menu.repartition') ?></a>
	</li>
</ul>
