<ul class="nav nav-list aside">
	<li class="nav-header"><?= _t('gen.menu.configuration') ?></li>
	<li class="item<?= Base_Request::actionName() === 'display' ? ' active' : '' ?>">
		<a href="<?= _url('configure', 'display') ?>"><?= _t('gen.menu.display') ?></a>
	</li>
	<li class="item<?= Base_Request::actionName() === 'reading' ? ' active' : '' ?>">
		<a href="<?= _url('configure', 'reading') ?>"><?= _t('gen.menu.reading') ?></a>
	</li>
	<li class="item<?= Base_Request::actionName() === 'archiving' ? ' active' : '' ?>">
		<a href="<?= _url('configure', 'archiving') ?>"><?= _t('gen.menu.archiving') ?></a>
	</li>
	<li class="item<?= Base_Request::actionName() === 'integration' ? ' active' : '' ?>">
		<a href="<?= _url('configure', 'integration') ?>"><?= _t('gen.menu.sharing') ?></a>
	</li>
	<li class="item<?= Base_Request::actionName() === 'shortcut' ? ' active' : '' ?>">
		<a href="<?= _url('configure', 'shortcut') ?>"><?= _t('gen.menu.shortcuts') ?></a>
	</li>
	<li class="item<?= Base_Request::actionName() === 'queries' ? ' active' : '' ?>">
		<a href="<?= _url('configure', 'queries') ?>"><?= _t('gen.menu.queries') ?></a>
	</li>
	<li class="item<?php echo Base_Request::controllerName() === 'user' &&
	                          Base_Request::actionName() === 'profile'? ' active' : ''; ?>">
		<a href="<?= _url('user', 'profile') ?>"><?= _t('gen.menu.user_profile') ?></a>
	</li>
	<li class="item<?= Base_Request::controllerName() === 'extension' ? ' active' : '' ?>">
		<a href="<?= _url('extension', 'index') ?>"><?= _t('gen.menu.extensions') ?></a>
	</li>
	<?= Base_ExtensionManager::callHook('menu_configuration_entry') ?>

	<?php if (RSSServer_Auth::hasAccess('admin')) { ?>
	<li class="nav-header"><?= _t('gen.menu.admin') ?></li>
	<li class="item<?= Base_Request::actionName() === 'system' ? ' active' : '' ?>">
		<a href="<?= _url('configure', 'system') ?>"><?= _t('gen.menu.system') ?></a>
	</li>
	<li class="item<?php echo Base_Request::controllerName() === 'user' &&
	                          Base_Request::actionName() === 'manage' ? ' active' : ''; ?>">
		<a href="<?= _url('user', 'manage') ?>"><?= _t('gen.menu.user_management') ?></a>
	</li>
	<li class="item<?= Base_Request::controllerName() === 'auth' ? ' active' : '' ?>">
		<a href="<?= _url('auth', 'index') ?>"><?= _t('gen.menu.authentication') ?></a>
	</li>
	<li class="item<?php echo Base_Request::controllerName() === 'update' &&
	                          Base_Request::actionName() === 'checkInstall' ? ' active' : ''; ?>">
		<a href="<?= _url('update', 'checkInstall') ?>"><?= _t('gen.menu.check_install') ?></a>
	</li>
	<?php if (!Base_Configuration::get('system')->disable_update) { ?>
	<li class="item<?php echo Base_Request::controllerName() === 'update' &&
	                          Base_Request::actionName() === 'index' ? ' active' : ''; ?>">
		<a href="<?= _url('update', 'index') ?>"><?= _t('gen.menu.update') ?></a>
	</li>
	<?php } ?>
	<?= Base_ExtensionManager::callHook('menu_admin_entry') ?>
	<?php } ?>
</ul>
