<?php
	$this->partial('nav_menu');

	$class = '';
	if (RSSServer_Context::$user_conf->hide_read_feeds &&
			RSSServer_Context::isStateEnabled(RSSServer_Entry::STATE_NOT_READ) &&
			!RSSServer_Context::isStateEnabled(RSSServer_Entry::STATE_READ)) {
		$class = ' state_unread';
	}
?>

<div id="stream" class="global<?= $class ?>">
<?php
	$params = Base_Request::fetchGET();
	unset($params['c']);
	unset($params['a']);
	$url_base = array(
		'c' => 'index',
		'a' => 'normal',
		'params' => $params,
	);

	foreach ($this->categories as $cat) {
		$feeds = $cat->feeds();
		$url_base['params']['get'] = 'c_' . $cat->id();

		if (!empty($feeds)) {
?>
	<div class="box category" data-unread="<?= $cat->nbNotRead() ?>">
		<div class="box-title"><a class="title" data-unread="<?= format_number($cat->nbNotRead()) ?>" href="<?= Base_Url::display($url_base) ?>"><?= $cat->name() ?></a></div>

		<ul class="box-content">
			<?php
				foreach ($feeds as $feed) {
					$nb_not_read = $feed->nbNotRead();
					$error = $feed->inError() ? ' error' : '';
					$empty = $feed->nbEntries() === 0 ? ' empty' : '';
					$url_base['params']['get'] = 'f_' . $feed->id();
			?>
			<li id="f_<?= $feed->id() ?>" class="item feed<?= $error, $empty, $feed->mute() ? ' mute' : '' ?>" data-unread="<?= $feed->nbNotRead() ?>" data-priority="<?= $feed->priority() ?>">
				<?php if (RSSServer_Context::$user_conf->show_favicons): ?><img class="favicon" src="<?= $feed->favicon() ?>" alt="✇" loading="lazy" /><?php endif; ?>
				<a class="item-title" data-unread="<?= format_number($feed->nbNotRead()) ?>" href="<?= Base_Url::display($url_base) ?>"><?= $feed->name() ?></a>
			</li>
			<?php } ?>
		</ul>
	</div>
<?php
		}
	}
?>
</div>

<div id="overlay">
	<a class="close" href="#"><?= _i('close') ?></a>
</div>
<div id="panel"<?= RSSServer_Context::$user_conf->display_posts ? '' : ' class="hide_posts"' ?>>
</div>
