<?php
	$url_next = Base_Request::currentRequest();
	$url_next['params']['next'] = RSSServer_Context::$next_id;
	$url_next['params']['state'] = RSSServer_Context::$state;
	$url_next['params']['ajax'] = 1;

	$url_mark_read = array(
		'c' => 'entry',
		'a' => 'read',
		'params' => array(
			'get' => RSSServer_Context::currentGet(),
			'nextGet' => RSSServer_Context::$next_get,
			'idMax' => RSSServer_Context::$id_max,
			'search' => htmlspecialchars_decode(RSSServer_Context::$search, ENT_QUOTES),
			'state' => RSSServer_Context::$state,
		)
	);
?>

<form id="mark-read-pagination" method="post">
<input type="hidden" name="_csrf" value="<?= RSSServer_Auth::csrfToken() ?>" />
<ul class="pagination">
	<li class="item pager-next">
	<?php if (RSSServer_Context::$next_id) { ?>
		<a id="load_more" href="<?= Base_Url::display($url_next) ?>">
			<?= _t('gen.pagination.load_more') ?>
		</a>
	<?php } elseif ($url_mark_read) { ?>
		<button id="bigMarkAsRead"
		        class="as-link <?= RSSServer_Context::$user_conf->reading_confirm ? 'confirm" disabled="disabled' : '' ?>"
		        form="mark-read-pagination"
		        formaction="<?= Base_Url::display($url_mark_read) ?>"
		        type="submit">
			<?= _t('gen.pagination.nothing_to_load') ?><br />
			<span class="bigTick">✓</span><br />
			<?= _t('gen.pagination.mark_all_read') ?>
		</button>
	<?php } else { ?>
		<a id="bigMarkAsRead" href=".">
			<?= _t('gen.pagination.nothing_to_load') ?><br />
		</a>
	<?php } ?>
	</li>
</ul>
</form>
